import type { Metadata } from "next";
import { Orbitron } from "next/font/google";
import "./globals.css";
import Navigation from "./ui/components/navigation/navigation";

const orbitron = Orbitron({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={orbitron.className}>
        <Navigation />
        {children}
        </body>
    </html>
  );
}
